### ISSUE TITLE
 Error: Node's Buffer() not available

### ISSUE THREAD

**Issue by leonardo-sj** [oliver-moran/jimp#280]
Hi,

I am developing an single page app with vue-cli webpack-simple. The only dependencies are firebase components and this library.
The Chrome console is showing the error below:

```
Uncaught Error: Node's Buffer() not available
    at Object.eval (eval at <anonymous> (build.js:1322), <anonymous>:53:11)
    at eval (eval at <anonymous> (build.js:1322), <anonymous>:129:30)
    at Object.<anonymous> (build.js:1322)
    at __webpack_require__ (build.js:658)
    at fn (build.js:86)
    at eval (eval at <anonymous> (build.js:1239), <anonymous>:8:63)
    at Object.<anonymous> (build.js:1239)
    at __webpack_require__ (build.js:658)
    at fn (build.js:86)
    at eval (eval at <anonymous> (build.js:1746), <anonymous>:7:3)
```

**Comment by Iwasawafag** [comment]
Since you're using Webpack, you can easily make these [`Buffer`](https://www.npmjs.com/package/buffer)s available in your runtime under the same name with Webpack's [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/)

**Comment by latchuk** [comment]
I'm using Angular2 in my Project and I have the same problem here. Can you have a sample of your solution with Webpack's ProvidePlugin?

**Comment by hia** [comment]
@Iwasawafag  hi.

**Comment by hia** [comment]
@Iwasawafag  hi.

**Comment by hia** [comment]
@Iwasawafag  hi

i have some problem. and i`m use webpack+react+jimp:

when i config webpack like that:

```
webpackConfig.plugins.push(new webpack.ProvidePlugin({
        'window.Buffer': 'buffer'
 }));

```

in code can get window.Buffer object,

```
console.log(window.Buffer); #can console object

```

but jimp still tell me "Node's Buffer() not available".

can you help me ?

**Comment by hia** [comment]
@leo-one  did you resolve you`s problem ?

**Comment by Iwasawafag** [comment]
Hello.

Sorry, last time I haven't really tested what I suggested about ProvidePlugin. I was pretty positive that it should have solved the error you were seeing but just now I tried it and had no success. For some reason it only replaced references to `window.Buffer` in my code and not in the code of the module. Which is a little weird, because that works perfectly fine for jQuery. 

I was able to get a little further by manually assigning `window.Buffer = require('buffer');` from my code as well as by using imports-loader, but it still didn't work – errored out when `mime` module tried to require `fs`.

What I found though is that `/browser/lib/jimp.js` [from npm](https://unpkg.com/jimp@0.2.28/browser/lib/jimp.js) is very different from the [same file in the repository](https://cdn.rawgit.com/oliver-moran/jimp/a74714f/browser/lib/jimp.js) 

Unfortunately right now I'm very limited on time, and can't check if version from the repo will work. From a quick look at the code – chances are highter, but it's still will be trying to require Node-specific modules. Webpack 2 can provide some of those [(documentation)](https://webpack.js.org/configuration/node/) so maybe with right configuration it will work.

I guess it's worth mentioning that I don't know much about browser version of Jimp except that it's here and that it's implementation is/was hacky. I'm sorry I couldn't be more helpful.

**Comment by hia** [comment]
@Iwasawafag 
 thank you very much all the same ,for you help ~

**Comment by mcarlucci** [comment]
+1

**Comment by keatz55** [comment]
+1

**Comment by steven1mcmurray** [comment]
+1

**Comment by TimvdLippe** [comment]
Reverting to 0.2.27 seems to fix this issue. The 0.2.28 release seems to explicitly mention it broke the browser version. Not sure why this was done in a patch version :thinking:

**Comment by bufface** [comment]
I'm still having the same issue, but a coworker found a solution just importing `jimp/browser` instead of `jimp`

**Comment by westlakem** [comment]
@bufface Can you specify?  when I switch to `require('jimp/browser')` or your listed `require('jimp/browser/lib/jimp');` I get a `Module not found: Error: Can't resolve 'jimp/browser'` error

**Comment by bufface** [comment]
@westlakem here is my code (It's exactly how you're using it):
```javascript
require('jimp/browser/lib/jimp');
const jimp = window.Jimp;
```
Btw: this is the version that we are using:
`"jimp": "0.2.27"`

**Comment by westlakem** [comment]
@bufface Yea, 0.2.28 broke it... it works with 0.2.27

**Comment by bufface** [comment]
@leonardo-sj I think you can close this issue.

**Comment by gabor** [comment]
@bufface i don't think the issue has been fixed yet. the current version of the software has this bug.

**Comment by westlakem** [comment]
@bufface @gabor @leonardo-sj  I agree, the issue should not be closed as this breaks the ability to upgrade.  Issues should be made for the most current version of the tool, and left open until the most recent version of the tool doesn't have the issue anymore.

**Comment by tiokadams20** [comment]
+1

**Comment by kangkon** [comment]
I am using react, It still shows error `Error: Node's Buffer() not available` even after using jimp version `0.2.27`. with the following code
```
require('jimp/browser/lib/jimp');
const jimp = window.Jimp;
```

**Comment by karanmartian** [comment]
any solution for this guys. Whats the correct way to use jimp with react?

**Comment by kangkon** [comment]
Only solution to this problem i found is...  Rendering your node project as a server side app, so that node can use a buffer to load and process images.

**Comment by progmem64** [comment]
I confirm that this is a **regression** bug.
It is working fine with version: 0.2.27, breaks with current version 0.2.28.
Provide-plugin, etc. does not work and i did not have the time to mess with the code.
What scares me is the fact that this issue is open since exactly one year (25 May), four days after Olivers last commit called: "_browser version broken in this release_" (referencing to 0.2.28).

**Comment by hipstersmoothie** [comment]
The last release for sure doesn't work. But latest master seems to 

```
var Jimp = require("jimp");

var url = "https://upload.wikimedia.org/wikipedia/commons/0/01/Bot-Test.jpg";

window.Jimp.read(url).then(function (image) {
    image.greyscale().getBuffer(window.Jimp.MIME_JPEG, onBuffer);
}).catch(function (err) {
    console.error(err);
})

function onBuffer (err, buffer) {
    if (err) throw err;
    console.log(buffer);
}
```

This successfully logs the base64 for the jpeg image. I'm think that all that is needed is a new release, since it seems like the `Buffer` error has been fixed since v0.2.28

**Comment by hipstersmoothie** [comment]
Should be good in latest release. Feel free to open more issues if the problem persists!

**Comment by chrisheseltine** [comment]
Confirmed fixed in latest

**Comment by tadiraman** [comment]
I am using "jimp": "^0.13.0". getting this issue..

**Comment by progmars** [comment]
The same with 1.6.0. How to use Jimp in browser environment properly?
